"""Reorder table creation and fix relationships

Revision ID: 3b293052e47b
Revises: cb5a966fe19c
Create Date: 2024-09-13 00:58:47.115719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b293052e47b'
down_revision: Union[str, None] = 'cb5a966fe19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_content', table_name='comments')
    op.add_column('recipes', sa.Column('title', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('description', sa.String(), nullable=True))
    op.drop_index('ix_recipes_ingredients', table_name='recipes')
    op.drop_index('ix_recipes_instructions', table_name='recipes')
    op.drop_index('ix_recipes_name', table_name='recipes')
    op.create_index(op.f('ix_recipes_title'), 'recipes', ['title'], unique=False)
    op.drop_column('recipes', 'name')
    op.drop_column('recipes', 'instructions')
    op.drop_column('recipes', 'ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredients', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('instructions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_recipes_title'), table_name='recipes')
    op.create_index('ix_recipes_name', 'recipes', ['name'], unique=False)
    op.create_index('ix_recipes_instructions', 'recipes', ['instructions'], unique=False)
    op.create_index('ix_recipes_ingredients', 'recipes', ['ingredients'], unique=False)
    op.drop_column('recipes', 'description')
    op.drop_column('recipes', 'title')
    op.create_index('ix_comments_content', 'comments', ['content'], unique=False)
    # ### end Alembic commands ###
