"""drop unnecessary tables.

Revision ID: 72337b3f10b5
Revises: 3730fa1f57a3
Create Date: 2024-05-15 23:19:22.618491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72337b3f10b5'
down_revision: Union[str, None] = '3730fa1f57a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_category', table_name='category')
    op.drop_index('ix_category_id', table_name='category')
    op.drop_table('category')
    op.drop_index('ix_tags_id', table_name='tags')
    op.drop_index('ix_tags_tag', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tags_pkey')
    )
    op.create_index('ix_tags_tag', 'tags', ['tag'], unique=False)
    op.create_index('ix_tags_id', 'tags', ['id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_pkey')
    )
    op.create_index('ix_category_id', 'category', ['id'], unique=False)
    op.create_index('ix_category_category', 'category', ['category'], unique=False)
    # ### end Alembic commands ###
